// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqntyfjpfyvmrwsxhtto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxbnR5ZmpwZnl2bXJ3c3hodHRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMjQ4MzcsImV4cCI6MjA2NzgwMDgzN30.nTmrj6WgVyjqOsMHw6ksrxhZXir6ySSy2EKEQL29p94";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});